config/routes.rb
Huginn::Application.routes.draw do
  resources :agents do
    member do
      post :run
      post :handle_details_post
      delete :remove_events
    end

    collection do
      post :propagate
      get :type_details
      get :event_descriptions
      get :diagram
    end

    resources :logs, :only => [:index] do
      collection do
        delete :clear
      end
    end
  end

  resources :events, :only => [:index, :show, :destroy] do
    member do
      post :reemit
    end
  end

  resources :user_credentials, :except => :show

  match "/worker_status" => "worker_status#show"

  post "/users/:user_id/update_location/:secret" => "user_location_updates#create"

  match "/users/:user_id/web_requests/:agent_id/:secret" => "web_requests#handle_request", :as => :web_requests
  post "/users/:user_id/webhooks/:agent_id/:secret" => "web_requests#handle_request" # legacy

# To enable DelayedJobWeb, see the 'Enable DelayedJobWeb' section of the README.
#  match "/delayed_job" => DelayedJobWeb, :anchor => false

  devise_for :users, :sign_out_via => [ :post, :delete ]

  match "/about" => "home#about"
  root :to => "home#index"
end

app/models/user_credential.rb
class UserCredential < ActiveRecord::Base
  MODES = %w[text java_script]

  attr_accessible :credential_name, :credential_value, :mode

  belongs_to :user

  validates_presence_of :credential_name
  validates_presence_of :credential_value
  validates_inclusion_of :mode, :in => MODES
  validates_presence_of :user_id
  validates_uniqueness_of :credential_name, :scope => :user_id

  before_validation :default_mode_to_text
  before_save :trim_fields

  protected

  def trim_fields
    credential_name.strip!
    credential_value.strip!
  end

  def default_mode_to_text
    self.mode = 'text' unless mode.present?
  end
end

app/controllers/user_credentials_controller.rb
class UserCredentialsController < ApplicationController
  def index
    @user_credentials = current_user.user_credentials.page(params[:page])

    respond_to do |format|
      format.html
      format.json { render json: @user_credentials }
    end
  end

  def new
    @user_credential = current_user.user_credentials.build

    respond_to do |format|
      format.html
      format.json { render json: @user_credential }
    end
  end

  def edit
    @user_credential = current_user.user_credentials.find(params[:id])
  end

  def create
    @user_credential = current_user.user_credentials.build(params[:user_credential])

    respond_to do |format|
      if @user_credential.save
        format.html { redirect_to user_credentials_path, notice: 'Your credential was successfully created.' }
        format.json { render json: @user_credential, status: :created, location: @user_credential }
      else
        format.html { render action: "new" }
        format.json { render json: @user_credential.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user_credential = current_user.user_credentials.find(params[:id])

    respond_to do |format|
      if @user_credential.update_attributes(params[:user_credential])
        format.html { redirect_to user_credentials_path, notice: 'Your credential was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_credential.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user_credential = current_user.user_credentials.find(params[:id])
    @user_credential.destroy

    respond_to do |format|
      format.html { redirect_to user_credentials_path }
      format.json { head :no_content }
    end
  end
end

app/views/user_credentials/_form.html.erb
<%= form_for(@user_credential, :method => @user_credential.new_record? ? "POST" : "PUT") do |f| %>
  <% if @user_credential.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_credential.errors.count, "error") %> prohibited this Credential from being saved:</h2>
      <ul>
      <% @user_credential.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :credential_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :credential_name, :class => 'span4' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :mode, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :mode, options_for_select(UserCredential::MODES.map {|s| [s.classify, s] }, @user_credential.mode), {}, :class => 'span4' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :credential_value, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :credential_value, :class => 'span8', :rows => 10 %>
      <div id="ace-credential-value"></div>
    </div>
  </div>

  <div class='form-actions' style='clear: both'>
    <%= f.submit "Save Credential", :class => "btn btn-primary" %>
  </div>
<% end %>

<%= javascript_include_tag "user_credentials" %>

app/views/user_credentials/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class='span12'>
      <div class="page-header">
        <h2>
          Editing your Credential
        </h2>
      </div>

      <%= render 'form' %>

      <div class="btn-group">
        <%= link_to '<i class="icon-chevron-left"></i> Back'.html_safe, user_credentials_path, class: "btn" %>
      </div>
    </div>
  </div>
</div>

app/views/user_credentials/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='span12'>
      <div class="page-header">
        <h2>
          Your Credentials
        </h2>
      </div>

      <blockquote>
        Credentials are used to store values used by many Agents. Examples might include "twitter_consumer_secret",
        "user_full_name", or "user_birthday".
      </blockquote>

      <table class='table table-striped'>
        <tr>
          <th>Name</th>
          <th>Value</th>
        </tr>

        <% @user_credentials.each do |user_credential| %>
          <tr>
            <td><%= user_credential.credential_name %></td>
            <td>
              <%= truncate user_credential.credential_value %>
              <div class="btn-group" style="float: right">
                <%= link_to 'Edit', edit_user_credential_path(user_credential), class: "btn btn-mini" %>
                <%= link_to 'Delete', user_credential_path(user_credential), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-mini" %>
              </div>
            </td>
          </tr>
        <% end %>
      </table>

      <%= paginate @user_credentials, :theme => 'twitter-bootstrap' %>

      <br/>

      <div class="btn-group">
        <%= link_to '<i class="icon-plus"></i> New Credential'.html_safe, new_user_credential_path, class: "btn" %>
      </div>
    </div>
  </div>
</div>

app/views/user_credentials/new.html.erb
<div class='container'>
  <div class='row'>
    <div class='span12'>
      <div class="page-header">
        <h2>
          Create a new Credential
        </h2>
      </div>

      <%= render 'form' %>

      <div class="btn-group">
        <%= link_to '<i class="icon-chevron-left"></i> Back'.html_safe, user_credentials_path, class: "btn" %>
      </div>
    </div>
  </div>
</div>