config/routes.rb
Huginn::Application.routes.draw do
  resources :agents do
    member do
      post :run
      post :handle_details_post
      delete :remove_events
    end

    collection do
      post :propagate
      get :type_details
      get :event_descriptions
      get :diagram
    end

    resources :logs, :only => [:index] do
      collection do
        delete :clear
      end
    end
  end

  resources :events, :only => [:index, :show, :destroy] do
    member do
      post :reemit
    end
  end

  resources :user_credentials, :except => :show

  match "/worker_status" => "worker_status#show"

  post "/users/:user_id/update_location/:secret" => "user_location_updates#create"

  match "/users/:user_id/web_requests/:agent_id/:secret" => "web_requests#handle_request", :as => :web_requests
  post "/users/:user_id/webhooks/:agent_id/:secret" => "web_requests#handle_request" # legacy

# To enable DelayedJobWeb, see the 'Enable DelayedJobWeb' section of the README.
#  match "/delayed_job" => DelayedJobWeb, :anchor => false

  devise_for :users, :sign_out_via => [ :post, :delete ]

  match "/about" => "home#about"
  root :to => "home#index"
end

app/models/event.rb
require 'json_serialized_field'

# Events are how Huginn Agents communicate and log information about the world.  Events can be emitted and received by
# Agents.  They contain a serialized `payload` of arbitrary JSON data, as well as optional `lat`, `lng`, and `expires_at`
# fields.
class Event < ActiveRecord::Base
  include JSONSerializedField

  attr_accessible :lat, :lng, :payload, :user_id, :user, :expires_at

  acts_as_mappable

  json_serialize :payload

  belongs_to :user
  belongs_to :agent, :counter_cache => true, :touch => :last_event_at

  scope :recent, lambda { |timespan = 12.hours.ago|
    where("events.created_at > ?", timespan)
  }

  after_create :possibly_propagate

  # Emit this event again, as a new Event.
  def reemit!
    agent.create_event :payload => payload, :lat => lat, :lng => lng
  end

  # Look for Events whose `expires_at` is present and in the past.  Remove those events and then update affected Agents'
  # `events_counts` cache columns.  This method is called by bin/schedule.rb periodically.
  def self.cleanup_expired!
    affected_agents = Event.where("expires_at IS NOT NULL AND expires_at < ?", Time.now).group("agent_id").pluck(:agent_id)
    Event.where("expires_at IS NOT NULL AND expires_at < ?", Time.now).delete_all
    Agent.where(:id => affected_agents).update_all "events_count = (select count(*) from events where agent_id = agents.id)"
  end

  protected
  def possibly_propagate
    #immediately schedule agents that want immediate updates
    propagate_ids = agent.receivers.where(:propagate_immediately => true).pluck(:id)
    Agent.receive!(:only_receivers => propagate_ids) unless propagate_ids.empty?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :load_event, :except => :index

  def index
    if params[:agent]
      @agent = current_user.agents.find(params[:agent])
      @events = @agent.events.page(params[:page])
    else
      @events = current_user.events.preload(:agent).page(params[:page])
    end

    respond_to do |format|
      format.html
      format.json { render json: @event }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @event }
    end
  end

  def reemit
    @event.reemit!
    redirect_to :back, :notice => "Event re-emitted"
  end

  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_path }
      format.json { head :no_content }
    end
  end

  private

  def load_event
    @event = current_user.events.find(params[:id])
  end
end

app/views/events/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='span12'>
      <div class="page-header">
        <h2>
          Your Events <%= @agent && "from #{@agent.name}" %>
        </h2>
      </div>

      <table class='table table-striped events'>
        <tr>
          <th>Source</th>
          <th>Created</th>
          <th>Payload</th>
          <th></th>
        </tr>

      <% @events.each do |event| %>
        <% next unless event.agent %>
        <tr>
          <td><%= link_to event.agent.name, agent_path(event.agent) %></td>
          <td><%= time_ago_in_words event.created_at %> ago</td>
          <td class='payload'><%= truncate event.payload.to_json, :length => 90, :omission => "" %></td>
          <td>
            <div class="btn-group">
              <%= link_to 'Show', event_path(event), class: "btn btn-mini" %>
              <%= link_to 'Re-emit', reemit_event_path(event), method: :post, data: { confirm: 'Are you sure you want to duplicate this event and emit the new one now?' }, class: "btn btn-mini" %>
              <%= link_to 'Delete', event_path(event), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-mini" %>
            </div>
          </td>
        </tr>
      <% end %>
      </table>

      <%= paginate @events, :theme => 'twitter-bootstrap' %>

      <br />

      <% if @agent %>
        <div class="btn-group">
          <%= link_to '<i class="icon-chevron-left"></i> Back'.html_safe, agents_path, class: "btn" %>
          <%= link_to '<i class="icon-random""></i> See all events'.html_safe, events_path, class: "btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='span12'>
      <div class="page-header">
        <h2>Event from <%= @event.agent.name %></h2>
      </div>

      <p>
        <b>Expires in:</b>
        <%= @event.expires_at ? time_ago_in_words(@event.expires_at) : 'never' %>
      </p>

      <p>
        <b>Payload:</b>
        <pre><%= Utils.pretty_jsonify @event.payload || {} %></pre>
      </p>

      <% if @event.lat && @event.lng %>
        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>

        <p>
          <b>Lat:</b>
          <%= @event.lat %>
          <br/>
          <b>Lng:</b>
          <%= @event.lng %>
        </p>

        <div id="map_canvas" style="width:400px; height:300px"></div>

        <script type="text/javascript">
          var mapOptions = {
            center: new google.maps.LatLng(<%= @event.lat %>, <%= @event.lng %>),
            zoom:15,
            mapTypeId:google.maps.MapTypeId.ROADMAP
          };

          var map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
        </script>

        <%= render "map_marker", :event => @event %>
      <% end %>

      <br />
      <div class="btn-group">
        <%= link_to '<i class="icon-chevron-left"></i> Back'.html_safe, events_path, class: "btn" %>
      </div>
    </div>
  </div>
</div>