config/routes.rb
Huginn::Application.routes.draw do
  resources :agents do
    member do
      post :run
      post :handle_details_post
      delete :remove_events
    end

    collection do
      post :propagate
      get :type_details
      get :event_descriptions
      get :diagram
    end

    resources :logs, :only => [:index] do
      collection do
        delete :clear
      end
    end
  end

  resources :events, :only => [:index, :show, :destroy] do
    member do
      post :reemit
    end
  end

  resources :user_credentials, :except => :show

  match "/worker_status" => "worker_status#show"

  post "/users/:user_id/update_location/:secret" => "user_location_updates#create"

  match "/users/:user_id/web_requests/:agent_id/:secret" => "web_requests#handle_request", :as => :web_requests
  post "/users/:user_id/webhooks/:agent_id/:secret" => "web_requests#handle_request" # legacy

# To enable DelayedJobWeb, see the 'Enable DelayedJobWeb' section of the README.
#  match "/delayed_job" => DelayedJobWeb, :anchor => false

  devise_for :users, :sign_out_via => [ :post, :delete ]

  match "/about" => "home#about"
  root :to => "home#index"
end

app/models/agents/manual_event_agent.rb
module Agents
  class ManualEventAgent < Agent
    cannot_be_scheduled!
    cannot_receive_events!

    description <<-MD
      Use this Agent to manually create Events for testing or other purposes.
    MD

    event_description "User determined"

    def default_options
      { "no options" => "are needed" }
    end

    def handle_details_post(params)
      if params['payload']
        create_event(:payload => params['payload'])
        { :success => true }
      else
        { :success => false, :error => "You must provide a JSON payload" }
      end
    end

    def working?
      true
    end

    def validate_options
    end
  end
end

app/views/agents/agent_views/manual_event_agent/_show.html.erb
<h3>Manually Create Events</h3>

<h4 id='event-creation-status'></h4>

<%= form_tag handle_details_post_agent_path(@agent), :id => "create-event-form" do %>
  <div class="control-group">
    <textarea rows="10" id="payload" name="payload" class="span8 payload-editor" data-height="200">
      {}
    </textarea>
  </div>

  <div class='form-actions' style='clear: both'>
    <%= submit_tag "Submit", :class => "btn btn-primary" %>
  </div>
<% end %>

<script>
  $(function () {
    var payloadJsonEditor = window.setupJsonEditor($(".payload-editor"));
    $("#create-event-form").submit(function (e) {
      e.preventDefault();
      var $form = $("#create-event-form");
      var $status = $("#event-creation-status");
      $.ajax({
        url: $form.attr('action'),
        method: "post",
        data: { payload: JSON.parse($form.find("textarea").val()) },
        dataType: "JSON",
        success: function(json) {
          if (json.success) {
            $status.text("Success!");
          } else {
            $status.text("An error occurred: " + json.error);
          }
        },
        error: function(response) {
          $status.text("An error occurred: " + response.responseText)
        }
      });
    });
  });
</script>